name             'nodechef'
maintainer       'Dmitry Skrinnik'
maintainer_email 'dmitry@skrinnik.com'
license          'All rights reserved'
description      'Installs/Configures nodechef'
long_description 'Installs/Configures nodechef'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'hostname'
depends 'sudo'
depends 'ssh_known_hosts'
depends 'ssmtp'
depends 'logrotate'
depends 'ufw'
depends 'nginx'
depends 'git'
depends 'ulimit'
depends 'mongodb'
depends 'python'
depends 'nodejs'
depends 'npm'

